[project]
name = "llama-index-pg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index>=0.12.43",
    "llama-index-vector-stores-postgres>=0.5.3",
]
